### PR TITLE
Add FernFlower for Mixin Debugging

### PR DESCRIPTION
**Pull request by glowredman**
Tranformed classes will be decompiled and copied to `./run/.mixin.out/java`.

This is the newest version I could find (from September 2020).

### CODE REVIEW

**Comment by drori200** [comment]
Care if i ask in where did you configure FF to save to `./run/.mixin.out/java`?

**Comment by glowredman** [comment]
I didn't configure it like that, SpongeMixins does it automatically.

**Comment by drori200** [comment]
Gotcha, seems good to me honestly.

**Review by mitchej123 — APPROVED** [review]
Seems fine.  Needs a rebase.

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
