### PR TITLE
Overwrite current ASM with a custom version.

### PR DESCRIPTION
**Pull request by drori200**
Fixes shading by using a custom version of ASM 5.0.3 that recognizes up to java 20.

### CODE REVIEW

**Comment by Glease** [comment]
not sure why would we need a custom jar... couldn't we just force a later version of asm being used instead?

**Comment by drori200** [comment]
This was the solution after trying to use newer versions of ASM.

**Comment by drori200** [comment]
The change we needed to do was just copy the java version fields from the modern ASM version to the old one so when trying to shade ASM thinks the library is compatible.

**Comment by Glease** [comment]
OK if we can't find a way out otherwise then this will have to make do.

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
