### PR TITLE
RFG IntelliJ fixes

### PR DESCRIPTION
**Pull request by eigenraven**
Update RFG, GTNHMixins with IntelliJ fixes:
 - Native run configurations now work again
 - Add support for multiple AT files separated by commas, requested by @OvermindDL1
 - Add a global override for the IDEA build type without the xml hacks from #132 
 - There's now a working MCDev plugin for IDEA 2022.3 you can download from <https://github.com/eigenraven/MinecraftDev/releases/tag/1.5.23-RFG> - uninstall the upstream mcdev and use this fork to get RFG support. Get SRG name, AT entry, etc. all work, including the Mixin plugin

### CODE REVIEW

**Comment by Glease** [comment]
Don't you still need to setup a root output location?

**Comment by Glease** [comment]
It appears unless someone go implement https://github.com/JetBrains/gradle-idea-ext-plugin/issues/108 we would have to stick to xml hacks.

**Comment by eigenraven** [comment]
Yeah, I just need to test the imports on projects without and with ipr files on your PR to make sure the xmls get generated correctly in each case.

**Comment by eigenraven** [comment]
@Glease I now implemented a full solution for adding the project output path that doesn't crash with ipr-format projects. (just using withIdeaXML was enough to trigger a crash in that case, it's probably a bug in the idea-ext plugin)

**Pull request merged**
