### PR TITLE
Bump FG to 1.2.12

### PR DESCRIPTION
**Pull request by drori200**
- Updates FG to 1.2.12: This fixes an issue with shading newer than java 8 libraries

### CODE REVIEW

**Review by eigenraven — DISMISSED** [review]

**Comment by drori200** [comment]
The action seems to fail but works fine locally. What should i do?

**Comment by eigenraven** [comment]
the error is `There is a binary discrepency between the expected input class net.minecraft.crash.CrashReport (b) and the actual class. Checksum on disk is 4bb6e52, in patch 242e6e52. Things are probably about to go very wrong. Did you put something into the jar file?`. Try cloning a fresh copy of the repo, maybe even clean your gradle cache and test locally from scratch

**Comment by drori200** [comment]
With setupDecompWorkspace the mod setups fine, with setupCIWorkspace we get the error. Stacktrace points to 
`ApplyBinPatchesTask.doTask(ApplyBinPatchesTask.java:87)`

**Comment by drori200** [comment]
Closing this as I can't seem to find any fix for it. If anyone else wishes to pick this up they can contact me on discord @ drori#4435

**Pull request closed without merging**
