### PR TITLE
Update buildscript maintenance workflow

### PR DESCRIPTION
**Pull request by MuXiu1997**
Tested and works fine

But may need to change the repository settings

Or maybe need to change the token

### CODE REVIEW

**Comment by MuXiu1997** [comment]
`.github/scripts/update_version` may no longer be required

**Comment by MuXiu1997** [comment]
@Dream-Master
If no one cares please close this pr

**Comment by Dream-Master** [comment]
We not close PR without a review

**Comment by Dream-Master** [comment]
We not close PR without a review

**Review by mitchej123 — APPROVED** [review]
Seems reasonable

**Pull request merged**
