### PR TITLE
add note that jabel may cause issues sometimes

### PR DESCRIPTION
**Pull request by bombcar**
See https://discord.com/channels/181078474394566657/603348502637969419/1198985740512657418

### CODE REVIEW

**Review by glowredman — COMMENTED** [review]
Afaik Jabel only breaks things when compiling Scala code

**Review by glowredman — COMMENTED** [review]
Tbh, I'd rather have the bs automatically disable Jabel if scala is detected. Then a simple note ("This property is automatically disabled when using Scala") should be enough.

**Comment by bombcar** [comment]
> Tbh, I'd rather have the bs automatically disable Jabel if scala is detected. Then a simple note ("This property is automatically disabled when using Scala") should be enough.

That's a much better option, but I don't know how to modify the buildscript to do that. If someone wants to they can delete this change.

**Comment by boubou19** [comment]
@glowredman @mitchej123 @eigenraven any plan to automagically disable jabel if compiling scala or should this be merged as is?

**Pull request closed without merging**
